config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_listener:
      branch: master
      repo: https://gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_listener
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_listener git:
        commands:
        - /usr/bin/env sh .sqa/script.randy-myrtle-setter.sh
        container: qc.acc_gummy-apricot-retriever
  QC.Doc:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_listener find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-platinum-beagle.sh
        container: qc.doc_silly-buff-lion
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_listener git:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-scarlet-chinchilla.sh
        container: qc.doc_cheeky-goldenrod-numbat
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_listener markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-gold-pinscher.sh
        container: qc.doc_shaky-brass-duck
  QC.Lic:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_listener licensee:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-buff-chihuahua.sh
        container: qc.lic_slaphappy-russet-chin
  QC.Sec:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_listener bandit:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-violet-dhole.sh
        container: qc.sec_blurry-saffron-penguin
  QC.Sty:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_listener flake8:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-burgundy-zonkey.sh
        container: qc.sty_droopy-goldenrod-dugong
  QC.Uni:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_listener pytest:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-gold-bird.sh
        container: qc.uni_goopy-violet-ray
  QC.Ver:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_listener get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-cobalt-okapi.sh
        container: qc.ver_hilly-green-squid
timeout: 5400
