config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_listener:
      branch: master
      repo: https://gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_listener
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_listener git:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-indigo-retriever.sh
        container: qc.acc_squirrely-ochre-flamingo
  QC.Doc:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_listener find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-razzmatazz-octopus.sh
        container: qc.doc_hilly-violet-chicken
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_listener git:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-red-newfoundland.sh
        container: qc.doc_sickly-cerise-catfish
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_listener markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-mauve-oriole.sh
        container: qc.doc_squirrely-sangria-leopard
  QC.Lic:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_listener licensee:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-cornflower-quail.sh
        container: qc.lic_snoopy-razzmatazz-bobcat
  QC.Sec:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_listener bandit:
        commands:
        - /usr/bin/env sh .sqa/script.homely-peach-toucan.sh
        container: qc.sec_boozy-myrtle-tarantula
  QC.Sty:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_listener flake8:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-magenta-squid.sh
        container: qc.sty_wheezy-eggplant-chinchilla
  QC.Uni:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_listener pytest:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-orchid-tapir.sh
        container: qc.uni_chewy-apricot-saola
  QC.Ver:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/esp_listener get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-grey-bloodhound.sh
        container: qc.ver_slimy-malachite-toucan
timeout: 5400
